# Enable peer dependencies
peer = true

# JSX settings for aisx files
jsxImportSource = "@/jsx-runtime"
jsx = "react-jsx"

# File-specific loaders
[loader]
".tsx" = "tsx"
".aisx.tsx" = "tsx"
".aisx.test.tsx" = "tsx"

